add some operators and utility funcs to BaseVector
randovania/retro-data-structures pull request #112
Opened 2023-12-13 22:26 UTC by duncathan

2023-12-13 22:49 UTC, henriquegemignani requested changes
Not sure I like multiplying vector by vector being per-conponent multiplication.

2023-12-13 22:49 UTC, henriquegemignani commented on src/retro_data_structures/properties/base_vector.py
> +    def rotate(self, rotation: BaseVector, center: BaseVector | None = None) -> typing_extensions.Self:
Add some docstring. And tests

2023-12-13 22:55 UTC, duncathan commented
> Not sure I like multiplying vector by vector being per-conponent multiplication.

It's what I'm used to from game engines I work with, and it's an operation I specifically needed in OPR. dot/cross products can be dedicated functions if we end up needing them imo

2023-12-13 23:55 UTC, henriquegemignani approved these changes

2025-04-11 03:24 UTC, duncathan commented
I've been waiting since December 2023 for tests to pass on this PR :skull:

2025-04-11 03:25 UTC, duncathan commented
and they didn't even pass now that they finally ran :sob:

2025-04-12 18:50 UTC, merged